[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "rules/gwmt.list"

[[rulesets]]
group = "ğŸ‡¨ğŸ‡³ å›½å†…åª’ä½“"
ruleset = "rules/gnmt.list"

[[rulesets]]
group = "ğŸ“º BILIBILI"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Bilibili.list"

[[rulesets]]
group = "ğŸ¤– ChatGPT"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/ChatGPT.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "rules/qqlj.list"

[[rulesets]]
group = "â“‚ å¾®è½¯æœåŠ¡"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥ä¿¡æ¯"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/qqzl.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/jdxz.list"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
